# Generated by Django 5.0.6 on 2024-08-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_sosalert_email_sosalert_latitude_sosalert_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DangerZones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cases', models.IntegerField()),
            ],
        ),
    ]
